In [76]:
import numpy as np
import matplotlib as plt



In [77]:
import pandas as pd
df = pd.read_csv(r"C:\Users\sande\OneDrive\Desktop\projject3\emi_prediction_dataset.csv")
df.head()

C:\Users\sande\AppData\Local\Temp\ipykernel_3984\1630192781.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\Users\sande\OneDrive\Desktop\projject3\emi_prediction_dataset.csv")


age  gender marital_status     education monthly_salary employment_type  \
0  38.0  Female        Married  Professional        82600.0         Private   
1  38.0  Female        Married      Graduate        21500.0         Private   
2  38.0    Male        Married  Professional        86100.0         Private   
3  58.0  Female        Married   High School        66800.0         Private   
4  48.0  Female        Married  Professional        57300.0         Private   

   years_of_employment company_type house_type  monthly_rent  ...  \
0                  0.9     Mid-size     Rented       20000.0  ...   
1                  7.0          MNC     Family           0.0  ...   
2                  5.8      Startup        Own           0.0  ...   
3                  2.2     Mid-size        Own           0.0  ...   
4                  3.4     Mid-size     Family           0.0  ...   

   existing_loans  current_emi_amount  credit_score  bank_balance  \
0             Yes             23700.0         660.0      303200.0   
1             Yes              4100.0         714.0       92500.0   
2              No                 0.0         650.0      672100.0   
3              No                 0.0         685.0      440900.0   
4              No                 0.0         770.0       97300.0   

   emergency_fund             emi_scenario  requested_amount requested_tenure  \
0         70200.0        Personal Loan EMI          850000.0               15   
1         26900.0  E-commerce Shopping EMI          128000.0               19   
2        324200.0            Education EMI          306000.0               16   
3        178100.0              Vehicle EMI          304000.0               83   
4         28200.0      Home Appliances EMI          252000.0                7   

   emi_eligibility  max_monthly_emi  
0     Not_Eligible            500.0  
1     Not_Eligible            700.0  
2         Eligible          27775.0  
3         Eligible          16170.0  
4     Not_Eligible            500.0  

[5 rows x 27 columns]

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 404800 entries, 0 to 404799
Data columns (total 27 columns):
 #   Column                  Non-Null Count   Dtype  
---  ------                  --------------   -----  
 0   age                     404800 non-null  object 
 1   gender                  404800 non-null  object 
 2   marital_status          404800 non-null  object 
 3   education               402396 non-null  object 
 4   monthly_salary          404800 non-null  object 
 5   employment_type         404800 non-null  object 
 6   years_of_employment     404800 non-null  float64
 7   company_type            404800 non-null  object 
 8   house_type              404800 non-null  object 
 9   monthly_rent            402374 non-null  float64
 10  family_size             404800 non-null  int64  
 11  dependents              404800 non-null  int64  
 12  school_fees             404800 non-null  float64
 13  college_fees            404800 non-null  float64
 14  travel_expenses     

In [79]:
df.shape

(404800, 27)

In [80]:
df.isnull().sum()

age                          0
gender                       0
marital_status               0
education                 2404
monthly_salary               0
employment_type              0
years_of_employment          0
company_type                 0
house_type                   0
monthly_rent              2426
family_size                  0
dependents                   0
school_fees                  0
college_fees                 0
travel_expenses              0
groceries_utilities          0
other_monthly_expenses       0
existing_loans               0
current_emi_amount           0
credit_score              2420
bank_balance              2426
emergency_fund            2351
emi_scenario                 0
requested_amount             0
requested_tenure             0
emi_eligibility              0
max_monthly_emi              0
dtype: int64

In [81]:
df.duplicated().sum()


np.int64(0)

In [82]:
df['age'].dtype

dtype('O')

In [83]:
df['age'].unique()

array([38.0, 58.0, 48.0, 32.0, 27.0, 47.0, 37.0, 31.0, 59.0, 49.0, 33.0,
       26.0, 39.0, 57.0, 28.0, '58', '38', '48', '32', '27', '37', '48.0',
       '33', '38.0', '49', '27.0', '31', '39', '47', '59', '32.0', '58.0',
       '57', '26', '28', '58.0.0', '39.0', '26.0', '37.0', '38.0.0',
       '32.0.0'], dtype=object)

In [84]:
df['age'] = df['age'].astype(str)


In [85]:
df['age'] = df['age'].str.replace('.0.0', '', regex=False)
df['age'] = df['age'].str.replace('.0', '', regex=False)


In [86]:
df['age'].unique()

array(['38', '58', '48', '32', '27', '47', '37', '31', '59', '49', '33',
       '26', '39', '57', '28'], dtype=object)

In [87]:
df['age'] = pd.to_numeric(df['age'], errors='coerce')

In [88]:
df['age'].unique()

array([38, 58, 48, 32, 27, 47, 37, 31, 59, 49, 33, 26, 39, 57, 28])

In [89]:
df['gender'].unique()

array(['Female', 'Male', 'female', 'male', 'M', 'MALE', 'F', 'FEMALE'],
      dtype=object)

In [90]:
# mapping = {"Female":'F' , "female": 'F', "f": 'F', "FEMALE": 'F',
#                  'Male': 'M', "male": 'M','MALE' : 'M'
#                  }


In [91]:
df['gender'] = df['gender'].str.lower()


In [92]:
mapping ={
    'male':'M',
    'female':'F',
    'm':'M',
    'f':'F'
}

In [93]:
df['gender'] = df['gender'].map(mapping)

In [94]:
df['gender'].unique()

array(['F', 'M'], dtype=object)

In [95]:
mapping = {
    'F': 1,
    'M': 0,
}

df['gender'] = df['gender'].map(mapping)

In [96]:
df['marital_status'].unique()

array(['Married', 'Single'], dtype=object)

In [97]:
mapping = {
    'Married': 1,
    'Single': 0,
}

df['marital_status'] = df['marital_status'].map(mapping)

In [98]:
df['monthly_salary'].unique()

array(['82600.0', '21500.0', '86100.0', ..., '56779.0', '56280.0',
       '55905.0'], shape=(13662,), dtype=object)

In [99]:
# df['monthly_salary'] = pd.to_numeric(
#     df['monthly_salary'],
#     errors='coerce'
# )


In [100]:
df['monthly_salary'].unique()

array(['82600.0', '21500.0', '86100.0', ..., '56779.0', '56280.0',
       '55905.0'], shape=(13662,), dtype=object)

In [101]:
# df['monthly_salary'] = df['monthly_salary'].astype(str)

In [102]:
# df['monthly_salary'] = df['monthly_salary'].str.replace('.0', '', regex=False)

In [103]:
df['monthly_salary'] = (
    df['monthly_salary']
    .astype(str)
    .str.replace(',', '', regex=False)
    .str.replace('₹', '', regex=False)
    .str.replace('rs', '', regex=False)
    .str.replace('.0.0', '', regex=False)
    .str.replace('.0', '', regex=False)
    .str.strip()
)

df['monthly_salary'] = pd.to_numeric(df['monthly_salary'])


In [104]:
df['monthly_salary'].unique()

array([82600, 21500, 86100, ..., 56779, 56280, 55905], shape=(12822,))

In [105]:
df['monthly_salary'].isnull().sum()

np.int64(0)

In [106]:
df['employment_type'].unique()

array(['Private', 'Government', 'Self-employed'], dtype=object)

In [107]:
mapping = {
    'Private': 0,
    'Government': 1,
    'Self-employed': 2
}

df['employment_type'] = df['employment_type'].map(mapping)

In [108]:
df['employment_type'].unique()

array([0, 1, 2])

In [109]:
df['company_type'].unique()

array(['Mid-size', 'MNC', 'Startup', 'Large Indian', 'Small'],
      dtype=object)

In [110]:
mapping = {
    'Small': 4, 
    'Mid-size': 0,
    'Large Indian': 3,
    'MNC':1, 'Startup': 2
}

df['company_type'] = df['company_type'].map(mapping)

In [111]:
df['house_type'].unique()

array(['Rented', 'Family', 'Own'], dtype=object)

In [112]:
mapping = {
    'Rented': 1,
    'Family': 2,
    'Own': 0
}

df['house_type'] = df['house_type'].map(mapping)

In [113]:
df['family_size'].unique()

array([3, 2, 4, 5, 1])

In [114]:
df['dependents'].unique()

array([2, 1, 3, 4, 0])

In [115]:
df['school_fees'].unique()

array([    0.,  5100., 11400.,  9400., 10200., 15000.,  8100., 10900.,
       12000.,  9100., 10800.,  9300., 11700.,  5500.,  5400.,  8000.,
        2400., 14400.,  3000., 12900.,  8300., 10600., 12300., 13800.,
        9900., 12500.,  5900.,  3900.,  8500., 12700.,  6800.,  7900.,
       11000.,  7700., 14100., 14300., 11200.,  4700., 11600.,  6500.,
        6200., 10300.,  9800.,  5700.,  5200.,  2500., 14800.,  2000.,
       14500.,  9500.,  5000.,  8800., 11800.,  5300.,  2700.,  9600.,
        7300.,  8200., 11300.,  4200.,  2200.,  3400.,  2100., 14700.,
       13500.,  8600., 10500.,  4400.,  3200., 10700.,  9000.,  3800.,
        5600.,  3500.,  7600., 13100.,  6600., 12800., 11100.,  3600.,
       13900.,  4500.,  7500.,  7400.,  2900., 11900.,  7100.,  4100.,
        8700., 14000., 12100.,  5800., 10000., 10100.,  3700.,  7000.,
       14900.,  3300.,  4300.,  4600., 14200.,  6300.,  2300.,  6100.,
       13000., 13200., 11500.,  8900., 13400.,  2600., 13600., 14600.,
      

In [116]:
df['school_fees'] = df['school_fees'].astype(int)


In [117]:
df['school_fees'].isnull().sum()


np.int64(0)

In [118]:
df['college_fees'].unique()

array([    0., 21300., 24100., 11300.,  8900., 15300., 20300., 22400.,
        6500., 15000., 12700., 17400., 14900., 24000., 22000., 12300.,
       17300.,  8300., 17600., 17900., 21900., 18900.,  5400., 10300.,
        9500., 18000., 15500., 10200.,  8600.,  5300., 20700., 20900.,
       10600.,  7900., 13400.,  5000., 21700., 19100., 16200., 24600.,
       19700., 24500., 12600., 15700.,  5800., 13600., 10700.,  9000.,
       21800., 15100.,  8500.,  6100.,  6800., 19800.,  5100., 16500.,
        6400., 19600., 11000., 11900., 16800., 14600., 10900., 14000.,
        5500., 20400., 17200., 21600., 16400., 24900., 21200.,  6000.,
       19200., 18300., 14300.,  9400., 16300.,  9800.,  7100.,  7400.,
       16700.,  9700.,  8400., 23200., 11600.,  5900., 11200., 10100.,
       23700.,  6300., 13700., 17000.,  9100., 12000., 20800., 20200.,
       10000., 14100., 17500., 22700., 19900., 23600., 22800.,  9200.,
       19300., 20500., 22600., 22900., 14800.,  7700., 13300., 14500.,
      

In [119]:
df['college_fees'] = df['college_fees'].astype(int)


In [120]:
df['travel_expenses'].unique()

array([ 7200.,  1400., 10200.,  6200.,  3600.,  3400.,  1600.,  5600.,
        6100., 11800.,  3100.,  6800.,  3800.,  4000.,  4900.,  6300.,
        8300.,  3200.,  9600.,  2600.,  5300.,  5500.,  8700.,  3000.,
        4200.,  3300.,  7100., 10800.,  4300., 11000.,  3900.,  9700.,
        2800.,  5800.,  7500.,  1900., 19400.,  9300.,  8400.,  1300.,
        8200.,  6900., 16000.,  4600., 12500.,  6500.,  6600.,  3500.,
        7000., 13700.,  9100.,  4700., 14000.,  2500.,  6000.,  5200.,
        5900.,  8100.,  4800., 15500.,  2700.,  5000., 16600.,  2100.,
        9000.,  9900.,  1000.,  6400.,  3700.,  9200.,  1100., 11600.,
       14700.,  2000.,  8500.,  5100., 19100.,  7400., 12600.,  8600.,
        8800.,  5400., 12100.,  7900., 13400.,  2200.,  4400.,  9400.,
        1500., 11200.,  7700.,  5700.,  4100.,  6700., 17800.,  4500.,
        2300., 15200., 11900.,  9500.,  1700., 10700.,  8900., 14600.,
        2900.,  2400., 13800., 16400., 13300., 12000.,  7800., 10300.,
      

In [121]:
df['travel_expenses'] = df['travel_expenses'].astype(int)


In [122]:
df['groceries_utilities'] = df['groceries_utilities'].astype(int)

In [123]:
df['groceries_utilities'].unique()

array([19500,  5400, 19400, 11900, 16200,  8200,  7300, 12300, 24100,
       11000,  8900, 14000, 10500, 27700, 10000, 15600,  8800, 13500,
       18500, 17600,  2600,  5500, 12700, 11100,  6500, 20300,  5800,
        6700,  8600, 23400,  5600, 22500, 10700, 11200, 26000,  8400,
       13600, 13200, 19800, 16500, 11400,  5300, 36400,  4900, 22700,
       16700,  3700, 24200, 15300, 23800, 14100,  6300, 18000, 10400,
       12900, 15100, 11800,  7500, 19100,  5900,  9300, 18400, 24000,
        9500, 17400,  9800,  7100,  8300,  9900,  8700,  7400, 12600,
       27500,  7900, 27600,  7800, 14400,  9100, 29100,  4800,  5700,
       23900, 31700, 29000,  9200, 12100, 15700,  2800, 14800, 12500,
       18700, 10600, 12800,  4200,  7600,  3100, 29200, 20200, 14900,
        8500,  8100,  4600, 13300,  3900, 28200,  9600, 16600,  6600,
        6900, 32600, 18300, 19000, 15900, 17800, 10800, 19300,  9400,
       14500, 25400, 25200, 10100, 20700,  6200, 13000, 10200, 17900,
       14300,  8000,

In [124]:
df['other_monthly_expenses'].unique()

array([13200.,  3500.,  6000.,  7900.,  8100.,  6700.,  4100.,  3000.,
        8300., 16500.,  9300.,  2500.,  3400.,  3900.,  9000.,  8400.,
        5400., 10300.,  6600.,  6900.,  7600.,  8000.,  1700.,  4500.,
       12100.,  8200.,  3300., 16100.,  2300.,  6400.,  9900., 10100.,
        5100., 25300.,  2900.,  6300., 11600.,  3700.,  4400., 10600.,
       14200.,  9800.,  3100.,  4300., 21700., 13000.,  7400.,  2100.,
        5600.,  4000., 10700., 12400.,  8700.,  9700., 12600.,  8800.,
        5000.,  7000.,  5700., 10200., 11300., 20400.,  3200., 14500.,
        6500.,  3800.,  8500.,  4600.,  6200., 15200.,  4800., 11100.,
       29100., 10800.,   800.,  9600.,  7700.,  7800., 12800.,  5300.,
       18000.,  4200.,  2400.,  2200.,  5500.,  3600.,  5800.,  1800.,
       12300., 15600.,  7300., 17200., 12000.,  5200., 14000.,  8900.,
       17800.,  7200., 16600.,  7500., 11900., 10400., 10500.,  2800.,
       18500.,  2000., 15000.,  1900., 14400.,  8600.,  2700.,  1100.,
      

In [125]:
df['other_monthly_expenses'] = df['other_monthly_expenses'].astype(int)


In [126]:
df['other_monthly_expenses'].isnull().sum()

np.int64(0)

In [127]:
df['max_monthly_emi'].unique()

array([  500. ,   700. , 27775. , ..., 38065.5, 49860. , 23730. ],
      shape=(15383,))

In [128]:
df['years_of_employment'].unique()

array([ 0.9,  7. ,  5.8,  2.2,  3.4,  5. , 36. , 12.9,  1.9,  7.5,  3.7,
        1.3,  3.2,  0.5, 26. ,  0.8,  4.2,  2.6,  3.9,  9.7,  4.7,  9.6,
        1.7,  9.4,  4.1,  1. ,  7.6, 16. ,  2.5,  1.6, 17.1,  6.6, 12.6,
        2.3,  4.5, 11.3, 10. ,  0.7,  3. ,  2.1,  2.7,  0.6,  8.6,  5.9,
        8.4, 12.4,  2.8, 15.9, 10.2,  1.2,  1.5, 14. ,  1.1,  6.5,  7.4,
        7.2, 20.7, 17.6, 16.6, 10.9, 20.6, 29.7,  8.5, 10.8, 14.2,  9.9,
       24.3,  9.1, 11.4, 11.8,  2. ,  6.2,  6.9,  5.2, 11.7, 18.1,  8.2,
        3.1,  3.3,  7.1,  5.5, 10.4,  4. ,  2.4,  8.3,  6.1,  4.4,  8.8,
        5.6,  5.4,  4.6, 17.8, 20.2, 22.7, 13.6,  8. ,  4.3,  2.9, 10.5,
       13.1, 14.1, 11.2,  4.8, 15.7,  6.3,  5.3, 18.9, 11.9, 21.3,  6.4,
       15.5,  3.5, 12. ,  1.8, 13.3,  1.4, 20.5,  8.9, 10.3,  8.1, 14.8,
       32. ,  5.1,  7.9, 21.9,  7.7, 15. , 25.8, 14.3,  6.7,  3.8, 21.8,
        9.2,  7.3,  5.7,  4.9,  9. , 15.1,  6.8, 15.3, 13. , 20. , 12.2,
       12.1, 13.8, 23.8, 12.8, 27.7,  6. , 18.2, 15

In [129]:
df['current_emi_amount'].unique()

array([23700.,  4100.,     0.,  9900., 33100.,  7100., 11300.,  6300.,
       18600., 10400., 21200.,  4800., 13600.,  5200.,  7800.,  5300.,
        6400., 34300.,  7500.,  6500.,  9300.,  3200., 29400., 11600.,
       20700.,  5700., 12300., 14300.,  6700., 14600.,  9000.,  3600.,
        4700., 14100., 21300.,  5900.,  6900.,  8900.,  5100., 11200.,
       10900.,  5600.,  2900., 17800.,  9500., 14400., 34000., 19000.,
        5500., 14200.,  9800.,  4300., 36700.,  5800., 12700.,  3300.,
        9700., 16700.,  9600., 22200.,  6200., 12200., 12600.,  8000.,
        4600., 12800., 18000., 14800., 14900.,  8100., 16100., 13200.,
        4000.,  2300., 17200., 13100.,  5000., 26800.,  8400.,  8200.,
        3000., 10600.,  7000., 10200., 12500., 21800.,  8500., 31200.,
       12000.,  7600., 15000.,  9400., 19200.,  7700., 13500., 23300.,
       28500., 10500., 20200., 12400.,  4400., 24800.,  8800.,  1900.,
       15900., 14000., 10800., 17400.,  6600., 10700., 28800., 24200.,
      

In [130]:
df['current_emi_amount'].isnull().sum()

np.int64(0)

In [131]:
df['existing_loans'].unique()

array(['Yes', 'No'], dtype=object)

In [132]:
mapping = {
    'Yes' :1 ,
    'No': 0
}
df['existing_loans'] = df['existing_loans'].map(mapping)

In [133]:
df['existing_loans'].isna().sum()

np.int64(0)

In [134]:
df['existing_loans'].unique()

array([1, 0])

In [135]:
df['emi_scenario'].unique()

array(['Personal Loan EMI', 'E-commerce Shopping EMI', 'Education EMI',
       'Vehicle EMI', 'Home Appliances EMI'], dtype=object)

In [136]:
mapping = {
    'Personal Loan EMI': 0,
    'E-commerce Shopping EMI': 1,
    'Education EMI': 2,
    'Vehicle EMI': 3,
    'Home Appliances EMI': 4
}

df['emi_scenario'] = df['emi_scenario'].map(mapping)


In [137]:
df['emi_scenario'].unique()

array([0, 1, 2, 3, 4])

In [138]:
df['requested_amount'].unique()

array([ 850000.,  128000.,  306000., ..., 1330000., 1203000., 1149000.],
      shape=(1491,))

In [139]:
df['requested_tenure'].unique()

array([15, 19, 16, 83,  7, 53, 11, 12, 14,  3, 77, 41, 21, 60, 61, 33, 35,
       57, 36, 63, 20, 75,  8, 23, 49, 45, 80, 34, 18, 59,  9, 48, 22, 42,
       13, 39, 55, 44, 37, 10, 25,  6, 24, 31, 28, 43, 29, 26, 58, 32, 69,
       46, 17,  5, 27, 30, 52, 66, 79, 40, 47, 51, 67, 74, 50, 38, 54, 76,
       64, 56, 71, 68, 73, 65, 72,  4, 81, 62, 70, 84, 78, 82])

In [140]:
df['education'].unique()

array(['Professional', 'Graduate', 'High School', 'Post Graduate', nan],
      dtype=object)

In [141]:
# df['education'].bfill()

In [142]:
df['education'].fillna(df['education'].mode()[0], inplace=True)


C:\Users\sande\AppData\Local\Temp\ipykernel_3984\2912846660.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['education'].fillna(df['education'].mode()[0], inplace=True)


In [143]:
mapping = {
    'High School': 1,
    'Graduate': 2,
    'Post Graduate': 3,
    'Professional': 4
}
df['education'] = df['education'].map(mapping)


In [144]:
df['education'].unique()

array([4, 2, 1, 3])

In [145]:
df['monthly_rent'].unique()

array([20000.,     0., 13500., ..., 54600.,  6143.,  8366.], shape=(4397,))

In [146]:
df['monthly_rent'].isna().sum()

np.int64(2426)

In [147]:
df['monthly_rent'].mean()

np.float64(5828.446490081367)

In [148]:
median = df['monthly_rent'].median()
median

np.float64(0.0)

In [149]:
df['monthly_rent'].fillna(median, inplace=True)


C:\Users\sande\AppData\Local\Temp\ipykernel_3984\186527587.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['monthly_rent'].fillna(median, inplace=True)


In [150]:
df['monthly_rent'].isna().sum()

np.int64(0)

In [151]:
df['credit_score'].unique()

array([ 660.,  714.,  650.,  685.,  770.,  792.,  741.,  623.,  712.,
        681.,  791.,  560.,  695.,  691.,  788.,  664.,  662.,  665.,
        655.,  719.,  663.,  765.,  804.,  755.,  808.,  710.,  769.,
        648.,  746.,  614.,  819.,  570.,  606.,  717.,  546.,  702.,
        718.,  694.,  729.,  732.,  705.,  850.,  697.,  737.,  670.,
        700.,  727.,  628.,  731.,  730.,  745.,  798.,  668.,  653.,
        735.,  630.,  704.,  686.,  716.,  678.,  578.,  762.,  693.,
        756.,  703.,  799.,  543.,  690.,  639.,  669.,  608.,  728.,
        676.,  777.,  636.,  840.,  616.,  849.,  688.,  722.,  725.,
        617.,  739.,  637.,  706.,  846.,  818.,  654.,  698.,  631.,
        753.,  790.,  713.,  738.,  696.,  748.,  821.,  626.,  618.,
        658.,  841.,  679.,  794.,  646.,  780.,  640.,  721.,  692.,
        673.,  656.,  843.,  715.,  701.,  754.,  805.,  595.,  576.,
        747.,   nan,  644.,  776.,  734.,  751., 1200.,  682.,  625.,
        720.,  811.,

In [152]:
df['credit_score'].isna().sum()

np.int64(2420)

In [153]:
df['credit_score'].mean()

np.float64(700.8562229733088)

In [154]:
df['credit_score'].median()

np.float64(701.0)

In [155]:
df['credit_score'].mode()[0]

np.float64(850.0)

In [156]:
df['credit_score'].fillna(df['credit_score'].median(), inplace=True)

C:\Users\sande\AppData\Local\Temp\ipykernel_3984\1758788495.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['credit_score'].fillna(df['credit_score'].median(), inplace=True)


In [157]:
df['bank_balance'].unique()

array(['303200.0', '92500.0', '672100.0', ..., '1026700.0', '302100.0.0',
       '141400.0.0'], shape=(12262,), dtype=object)

In [158]:
df['bank_balance'].unique()

array(['303200.0', '92500.0', '672100.0', ..., '1026700.0', '302100.0.0',
       '141400.0.0'], shape=(12262,), dtype=object)

In [159]:
df['bank_balance'].isnull().sum()

np.int64(2426)

In [160]:
df['bank_balance'] = (
    df['bank_balance']
    .str.replace(',', '', regex=False)
    .str.replace('₹', '', regex=False)
    .str.replace('rs', '', regex=False)
    .str.replace('.0.0', '', regex=False)
    .str.replace('.0', '', regex=False)
    .str.strip()
)

In [161]:
# df['bank_balance'] = pd.to_numeric(df['bank_balance'])
df['bank_balance'] = pd.to_numeric(df['bank_balance'], errors='coerce')


In [162]:
df['bank_balance'].isnull().sum()

np.int64(2440)

In [163]:
df['bank_balance'].mean()

np.float64(241688.96808827916)

In [164]:
df['bank_balance'].mode()[0]

np.float64(115800.0)

In [165]:
df['bank_balance'].fillna(df['bank_balance'].median(), inplace=True)


C:\Users\sande\AppData\Local\Temp\ipykernel_3984\2218495642.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['bank_balance'].fillna(df['bank_balance'].median(), inplace=True)


In [166]:
df['bank_balance'].isnull().sum()

np.int64(0)

In [167]:
df['emergency_fund'].unique()

array([ 70200.,  26900., 324200., ..., 470100., 711600., 525000.],
      shape=(5487,))

In [168]:
df['emergency_fund'].mean()

np.float64(96769.05173077832)

In [169]:
df['emergency_fund'].mode()[0]

np.float64(29100.0)

In [170]:
df['emergency_fund'].median()

np.float64(74000.0)

In [171]:
df['emergency_fund'].fillna(df['emergency_fund'].mode()[0], inplace=True)

C:\Users\sande\AppData\Local\Temp\ipykernel_3984\1773673317.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['emergency_fund'].fillna(df['emergency_fund'].mode()[0], inplace=True)


In [175]:
df['emi_eligibility'].unique()

array(['Not_Eligible', 'Eligible', 'High_Risk'], dtype=object)

In [178]:
mapping = {
    'Not_Eligible': 0,
    'Eligible': 1,
    'High_Risk': 2
}

df['emi_eligibility'] = df['emi_eligibility'].map(mapping)


In [179]:
df['emi_eligibility'].unique()

array([0, 1, 2])

In [176]:
df['max_monthly_emi'].unique()

array([  500. ,   700. , 27775. , ..., 38065.5, 49860. , 23730. ],
      shape=(15383,))

In [172]:
df['emergency_fund'].isna().sum()

np.int64(0)

In [180]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 404800 entries, 0 to 404799
Data columns (total 27 columns):
 #   Column                  Non-Null Count   Dtype  
---  ------                  --------------   -----  
 0   age                     404800 non-null  int64  
 1   gender                  404800 non-null  int64  
 2   marital_status          404800 non-null  int64  
 3   education               404800 non-null  int64  
 4   monthly_salary          404800 non-null  int64  
 5   employment_type         404800 non-null  int64  
 6   years_of_employment     404800 non-null  float64
 7   company_type            404800 non-null  int64  
 8   house_type              404800 non-null  int64  
 9   monthly_rent            404800 non-null  float64
 10  family_size             404800 non-null  int64  
 11  dependents              404800 non-null  int64  
 12  school_fees             404800 non-null  int64  
 13  college_fees            404800 non-null  int64  
 14  travel_expenses     

In [174]:
df.isna().sum()

age                       0
gender                    0
marital_status            0
education                 0
monthly_salary            0
employment_type           0
years_of_employment       0
company_type              0
house_type                0
monthly_rent              0
family_size               0
dependents                0
school_fees               0
college_fees              0
travel_expenses           0
groceries_utilities       0
other_monthly_expenses    0
existing_loans            0
current_emi_amount        0
credit_score              0
bank_balance              0
emergency_fund            0
emi_scenario              0
requested_amount          0
requested_tenure          0
emi_eligibility           0
max_monthly_emi           0
dtype: int64

In [181]:
# Import required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.linear_model import LinearRegression, Ridge, Lasso, SGDRegressor
# LinearRegression-OLS
# SGDRegressor-GradientDescent
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

In [ ]:
# df = pd.DataFrame(X, columns=['Feature'])
# df['Target'] = y
# df.head()

In [182]:
#classical -Logistic Regression
y_class = df['emi_eligibility']
X_class = df.drop(['emi_eligibility', 'max_monthly_emi'], axis=1) 

In [195]:
df['emi_eligibility'].value_counts()

emi_eligibility
0    312868
1     74444
2     17488
Name: count, dtype: int64

In [196]:
df['max_monthly_emi'].value_counts()

max_monthly_emi
500.00      106683
3080.00        513
4200.00        490
4620.00        479
6600.00        475
             ...  
17984.00         1
8503.88          1
33541.20         1
14201.60         1
19310.40         1
Name: count, Length: 15383, dtype: int64

In [183]:
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, 
#                                                     random_state=42)
from sklearn.model_selection import train_test_split

Xc_train, Xc_test, yc_train, yc_test = train_test_split(
    X_class, y_class, test_size=0.2, random_state=42
)


In [188]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score

In [ ]:
model1 = LogisticRegression()
model1.fit(Xc_train, yc_train)

C:\Users\sande\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [190]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

Xc_train_scaled = scaler.fit_transform(Xc_train)
Xc_test_scaled  = scaler.transform(Xc_test)


In [192]:
model = LogisticRegression(max_iter=1000)
model.fit(Xc_train, yc_train)

C:\Users\sande\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=1000)

In [193]:
# 4️⃣ Predict on the full dataset for visualization
y_predi = model.predict(X_class)
y_pred2 = model.predict(Xc_test)

In [194]:
model.coef_, model.intercept_

(array([[ 1.10132263e-04,  1.41705017e-06,  1.75430530e-06,
          3.18117943e-06, -3.60987635e-06,  4.81787025e-07,
         -3.16818587e-06,  5.36577710e-06,  3.31031818e-06,
          6.96827267e-05,  8.39034189e-06,  4.99847905e-06,
          8.60353318e-05,  8.34412729e-05, -6.82890631e-05,
         -6.95793107e-05, -7.30753281e-06,  3.20178467e-06,
          1.10237618e-04,  1.45394437e-03, -1.91642364e-06,
         -2.13923681e-07,  3.69221624e-06,  4.58888126e-06,
         -3.25292726e-04],
        [-5.54117432e-06, -2.61083640e-07,  2.09599403e-08,
          1.41733304e-06,  2.85465933e-06,  5.25594369e-07,
          1.38089210e-05, -7.77796743e-07, -7.00081555e-07,
         -5.40917342e-05, -8.45001538e-07, -2.99401507e-07,
         -6.00885725e-05, -5.89394308e-05,  6.90834872e-05,
          5.57441909e-05,  4.08862259e-07, -1.94855096e-06,
         -8.45940795e-05,  2.97777000e-04,  1.57821035e-06,
         -1.82287421e-09,  1.92381116e-06, -5.17764455e-06,
          3.3

In [184]:
##Linear Regression
y_reg = df['max_monthly_emi']
X_reg = df.drop(['max_monthly_emi', 'emi_eligibility'], axis=1)


In [185]:
Xr_train, Xr_test, yr_train, yr_test = train_test_split(
    X_reg, y_reg, test_size=0.2, random_state=42
)


In [186]:
model = LinearRegression()
model.fit(Xr_train, yr_train)

# # 4️⃣ Predict on the full dataset for visualization
y_pred = model.predict(X_reg)
y_pred1 = model.predict(Xr_test)


In [187]:
model.coef_, model.intercept_

(array([ 1.92617028e+00, -1.10528513e+01,  3.47987752e+01,  4.36600975e+02,
         2.19741027e-02,  9.14228442e+01,  3.69296330e+01,  7.55237947e+00,
        -2.31921365e+01, -3.23083109e-01, -2.43797149e+01, -2.43797149e+01,
        -3.10771226e-01, -2.60152627e-01,  3.32531678e-01,  3.47714479e-01,
         2.67706239e-02, -1.42386279e+03, -3.78489836e-01,  8.62715630e+00,
         1.03258941e-02,  1.02194613e-03,  6.65679287e+00, -2.56337667e-05,
         6.08903167e-01]),
 np.float64(-4330.875854302861))